// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Description sql.NullString
	Status      sql.NullString
	Created     sql.NullInt64
	Updated     sql.NullInt64
}
