// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (description, status, created, updated)
VALUES ($1, $2, $3, $4)
RETURNING id, description, status, created, updated
`

type CreateTodoParams struct {
	Description sql.NullString
	Status      sql.NullString
	Created     sql.NullInt64
	Updated     sql.NullInt64
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Description,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, description, status, created, updated FROM todos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, description, status, created, updated FROM todos
ORDER BY id
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET description = $2, status = $3, updated = $4
WHERE id = $1
RETURNING id, description, status, created, updated
`

type UpdateTodoParams struct {
	ID          int64
	Description sql.NullString
	Status      sql.NullString
	Updated     sql.NullInt64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.ID,
		arg.Description,
		arg.Status,
		arg.Updated,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
